defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  lint:
    <<: *defaults
    docker:
      - image: circleci/golang:1.8.1
    steps:
      - checkout
      - run:
          name: Install tools
          command: | 
            .circleci/install.sh

      - run:
          name: Run the linters
          command: make ci-linters

  publish:
    <<: *defaults
    docker:
      - image: circleci/python:3.6.5-stretch-node-browsers

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fd:ab:ac:70:6f:88:46:16:91:7c:f7:3d:82:9a:fa:f5"

      - run:
          name: Configure git
          command: |
            git config --global user.email "circleci@requestyoracks.org"
            git config --global user.name "CircleCI"

      - run:
          name: Install tools
          command: |
            .circleci/install.sh
            make setup

      - run:
          name: Package the charts
          command: make dist

      - run:
          name: Publish the charts
          command: make publish

workflows:
  version: 2
  lint-publish:
    jobs:
      - lint
      - publish:
          requires:
            - lint
          filters:
            branches:
              only: master
