# Default values for flower.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: requestyoracks/celery-flower
  tag: 0.9.2-1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5555

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - flower.192.168.99.100.nip.io
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  CELERY_BROKER_URL: redis://$(REDIS_MASTER_SERVICE_HOST):$(REDIS_MASTER_SERVICE_PORT)/0

configmap:
  FLOWER_PORT: "5555"
