# Default values for ryr-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: requestyoracks/api
  tag: 0.1.7
  pullPolicy: IfNotPresent

# Configure the Service
service:
  name: api
  type: ClusterIP
  externalPort: 8000
  internalPort: 8000

# Configure the ingress.
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - api.requestyoracks.org
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: []
resources: {}

# Configure the persistence.
# This also allows live reload in minikube.
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  hostPath:
    path: /data

# Environment.
env:
  DATABASE_URL:  postgres://postgres:$(postgres-password)@$(POSTGRESQL_SERVICE_HOST):$(POSTGRESQL_SERVICE_PORT)/postgres
  REDIS_URL: redis://$(redis-password)@$(REDIS_MASTER_SERVICE_HOST):$(REDIS_MASTER_SERVICE_PORT)

# Configmap for the API.
configmap:
  DJANGO_ALLOWED_HOSTS: api.requestyoracks.org
  DJANGO_CORS_ORIGIN_WHITELIST: www.requestyoracks.org
  DJANGO_SETTINGS_MODULE: api.settings.production
  RYR_API_API_OPTS: "--timeout 1800 --chdir /usr/src/app"
